steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/flask-site-429610/my-image:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/flask-site-429610/my-image:latest']

images:
  - 'asia.gcr.io/flask-site-429610/my-image:latest'


options:
  logging: CLOUD_LOGGING_ONLY